# Generated by Django 6.0.1 on 2026-02-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unified_requests", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="unifiedrequest",
            new_name="unified_req_request_c49539_idx",
            old_name="unified_requ_request_bcc4e6_idx",
        ),
        migrations.RenameIndex(
            model_name="unifiedrequest",
            new_name="unified_req_assigne_34e823_idx",
            old_name="unified_requ_assigne_2e4298_idx",
        ),
        migrations.RenameIndex(
            model_name="unifiedrequest",
            new_name="unified_req_source__0e3342_idx",
            old_name="unified_requ_source__5f39f7_idx",
        ),
    ]
