# Generated by Codex on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0010_providerspotlightitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerportfolioitem",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="providers/portfolio/%Y/%m/thumbs/",
            ),
        ),
        migrations.AddField(
            model_name="providerspotlightitem",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="providers/spotlights/%Y/%m/thumbs/",
            ),
        ),
    ]

