# Generated by Django 6.0.1 on 2026-02-23 22:41

import apps.verification.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_requirements_and_verifiedbadge_codes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="verificationrequirement",
            new_name="verificatio_code_290ca1_idx",
            old_name="verificatio_code_0d4980_idx",
        ),
        migrations.RenameIndex(
            model_name="verificationrequirement",
            new_name="verificatio_badge_t_25b8ef_idx",
            old_name="verificatio_badge_t_344f02_idx",
        ),
        migrations.RenameIndex(
            model_name="verifiedbadge",
            new_name="verificatio_user_id_9c9999_idx",
            old_name="verificatio_user_id_06295a_idx",
        ),
        migrations.AlterField(
            model_name="verificationrequirementattachment",
            name="file",
            field=models.FileField(
                upload_to="verification/requirements/%Y/%m/",
                validators=[
                    apps.verification.validators.validate_file_size,
                    apps.verification.validators.validate_extension,
                ],
            ),
        ),
    ]
