# Generated by Copilot

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("providers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtrasPortalSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "نشط"), ("inactive", "غير نشط")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("plan_title", models.CharField(blank=True, default="", max_length=120)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras_portal_subscription",
                        to="providers.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtrasPortalFinanceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                ("account_name", models.CharField(blank=True, default="", max_length=120)),
                ("iban", models.CharField(blank=True, default="", max_length=34)),
                (
                    "qr_image",
                    models.FileField(blank=True, null=True, upload_to="extras_portal/finance/%Y/%m/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras_portal_finance_settings",
                        to="providers.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtrasPortalScheduledMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=2000)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="extras_portal/messages/%Y/%m/%d/",
                    ),
                ),
                ("send_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "معلق"),
                            ("sent", "تم الإرسال"),
                            ("failed", "فشل"),
                            ("cancelled", "ملغي"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extras_portal_created_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_messages",
                        to="providers.providerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtrasPortalScheduledMessageRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "scheduled_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="extras_portal.extrasportalscheduledmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extras_portal_message_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="extrasportalscheduledmessagerecipient",
            constraint=models.UniqueConstraint(
                fields=("scheduled_message", "user"),
                name="uniq_extras_portal_scheduled_message_user",
            ),
        ),
    ]
